from enum import StrEnum

class ErrorCodes(StrEnum):
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    NO_CONTENT = "NO_CONTENT"
    INVALID_REQUEST = "INVALID_REQUEST"
    MISSING_PARAMETER = "MISSING_PARAMETER"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_PAYLOAD = "INVALID_PAYLOAD"
    INVALID_TOKEN = "INVALID_TOKEN"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    DATABASE_ERROR = "DATABASE_ERROR"
